name: palpet
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  image_picker: ^1.0.4
  intl: ^0.20.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/imgs/